// Generates src/runtime-worker.js — the runtime host, as a string, so a worker can be created from a
// blob (a worker script URL must be same-origin, and a package consumer must not have to serve one).
//
// The source of truth is `public/lean-worker.js`, which the demo serves directly. One implementation,
// two ways in; this script exists so the two cannot drift.
//
//   node scripts/sync-worker.mjs           # write it
//   node scripts/sync-worker.mjs --check   # fail if it is stale
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const SOURCE = fileURLToPath(new URL('../../../public/lean-worker.js', import.meta.url));
const TARGET = fileURLToPath(new URL('../src/runtime-worker.js', import.meta.url));

const HEADER = `// GENERATED by scripts/sync-worker.mjs from public/lean-worker.js — do not edit.
// The runtime host travels as a string because it has to be handed over as a blob: a worker script
// URL must be same-origin, and a packaged consumer has nowhere to serve one from.
`;

const source = await readFile(SOURCE, 'utf8');
// A JSON string literal, not a template literal: the worker is full of backticks and \${}.
const generated = `${HEADER}\nexport const RUNTIME_WORKER_SOURCE = ${JSON.stringify(source)};\n`;

if (process.argv.includes('--check')) {
	const existing = await readFile(TARGET, 'utf8').catch(() => '');
	if (existing !== generated) {
		console.error('src/runtime-worker.js is out of date. Run: npm run sync:worker');
		process.exit(1);
	}
	console.log('src/runtime-worker.js is in sync');
	process.exit(0);
}

await writeFile(TARGET, generated);
console.log(`src/runtime-worker.js written (${(generated.length / 1024).toFixed(1)} KB)`);
